// 提取问题,可能包含图片
// function getQuestionStr(className) {
//   const elements = document.querySelectorAll(className);
//   const result = Array.from(elements).map((element) => {
//     const question = extractContent(element);
//     const [maxMark, content] = getMaxMarkAndContent(question);
//     return content;
//   });
//   return result;
// }

// function getMaxMarkAndContent(str) {
//   // 1. 提取 [Maximum mark: 6] 里的数字
//   const markMatch = str.match(/\[Maximum mark:\s*(\d+)\]/);
//   const mark = markMatch ? markMatch[1] : null;

//   // 2. 提取后面的全部内容
//   const content = str.replace(/\[Maximum mark:\s*\d+\]\n?/, "");
//   return [mark, content];
// }

// function extractContent(node) {
//   let result = [];

//   node.childNodes.forEach((child) => {
//     if (child.nodeType === Node.ELEMENT_NODE) {
//       if (child.tagName.toLowerCase() === "img") {
//         result.push(`\n\n![SkillUpp Image](${child.src})\n\n`);
//       } else {
//         result.push(...extractContent(child)); // 递归遍历子节点
//       }
//     } else if (child.nodeType === Node.TEXT_NODE) {
//       const text = child.textContent.trim();
//       if (text) {
//         result.push(text);
//       }
//     }
//   });

//   return result.join("");
// }
// console.log(getQuestionStr(".css-9axr9m"));

import fs from "fs";
const filePath = "./Theme A All.json"; // 文件路径
const newPath = "./A1.1 - Water.json"; // 新文件路径
const questionArr = [
  "Which of the following is a reason why water is retained on Earth and does not escape into space?A.\\hspace{1em}Different patterns of rainfall across continentsB.\\hspace{1em}The gravitational pull of the MoonC.\\hspace{1em}Surface temperatures high enough to allow evaporationD.\\hspace{1em}Earth’s gravitational field",
  "What intermolecular bond is responsible for water's cohesive, adhesive and thermal properties?A.\\hspace{1em}Covalent bondB.\\hspace{1em}Hydrogen bondC.\\hspace{1em}Ionic bondD.\\hspace{1em}Metallic bond",
  "What property of water helps living organisms maintain their internal body temperature?A.\\hspace{1em}Thermal propertiesB.\\hspace{1em}Cohesive propertiesC.\\hspace{1em}Adhesive propertiesD.\\hspace{1em}Solvent properties",
  "What is the most accepted theory for the origin of water on Earth?A.\\hspace{1em}Asteroids from space containing ice arrived on Earth billions of years agoB.\\hspace{1em}Respiration from early organisms released water into the atmosphereC.\\hspace{1em}Heat from ancient deep-sea vents catalysed the reaction between hydrogen and oxygen atomsD.\\hspace{1em}Early volcanic eruptions, released steam into the atmosphere",
  "Which of the following is not soluble in water?A.\\hspace{1em}GlucoseB.\\hspace{1em}Amino AcidsC.\\hspace{1em}CholesterolD.\\hspace{1em}Sodium Chloride",
  "What substances are attracted to water and form intermolecular bonds with water molecules?A.\\hspace{1em}Insoluble substancesB.\\hspace{1em}Hydrophobic substancesC.\\hspace{1em}Hydrophilic substancesD.\\hspace{1em}Non-polar substances",
  "Which is the correctly annotated diagram of a molecule of water?\n\n![SkillUpp Image](https://assets.revisionvillage.com/public/question/edd73f4a-ca99-4c0a-8aa6-5dd7c70ee984/images/a5ccea10-4644-40e3-934c-b5de3575771e/BI1011iii.png)\n\n",
  "Outline how hydrogen bonds form between water molecules.[2]State one of the ways that hydrophilic substances interact with water.[1]State one of the ways that non-polar molecules interact with water.[1]Distinguish between cohesion and adhesion.[2]",
  "The micrograph below shows the longitudinal cross-section of a stem from a plant in thePinusgenus.  Xylem vessels are clearly visible.\n\n![SkillUpp Image](https://assets.revisionvillage.com/public/question/ce64231b-0a07-4418-a59e-8dfdae6072ce/images/a56a5858-4bcb-449c-b27e-2d6d5a622fdd/BI1046.png)\n\nMagnification: 100X[Source: From Berkshire Community College Bioscience Image Library. (2014).Radial section: Pinus stem magnification: 100x iron-alum hematoxylin and safranin stain. Wikimedia Commons. Retrieved April 29, 2022, from https://commons.wikimedia.org/wiki/File:Gymnosperm_Stem_Soft_Wood_in_Pinus_(36087426450).jpg.\nCopyright by CC BY CC0 1.0\n]The xylem is composed of hollow, tube-like tissues that transport water through capillary action. What property of water explains capillary action?A.\\hspace{1em}Melting pointB.\\hspace{1em}Adhesive propertiesC.\\hspace{1em}Specific heat capacityD.\\hspace{1em}Buoyant forces",
  "Which substance is insoluble in water and suitable for energy storage in animals?A.\\hspace{1em}StarchB.\\hspace{1em}GlucoseC.\\hspace{1em}RiboseD.\\hspace{1em}Glycogen",
  "The image shows the vascular tissue in the leaves of a corn plant (Zea mays). What property of water is not demonstrated in the vascular tissue of the plant?\n\n![SkillUpp Image](https://assets.revisionvillage.com/public/question/e57087dc-a110-4437-ad90-1eed35cfde39/images/2ff3d4f0-e8cd-4249-9307-e959ca83e346/BI1224.png)\n\n[Source: Adapted from Berkshire Community College  Bioscience Image Library. (2017, October 3).Angiosperm morphology: The closed and collateral vascular bundle in Zea. Flickr. Retrieved September 11, 2023, from https://www.flickr.com/photos/146824358@N03/37215761790. Copyright free]A.\\hspace{1em}CohesionB.\\hspace{1em}AdhesionC.\\hspace{1em}Universal solventD.\\hspace{1em}High thermal conductivity",
  "Which of the following is a reason that the Earth is considered to be in ‘The Goldilocks zone’, but Saturn is not?A.\\hspace{1em}The Earth is at an optimal distance from the Sun for water to be in three states, whereas Saturn has rings of iceB.\\hspace{1em}Saturn is able to form rings, but the Earth does not have ringsC.\\hspace{1em}The Earth is at an optimal distance from the Sun for water to remain liquid, whereas Saturn is notD.\\hspace{1em}The Sun is visible from Earth but not from Saturn",
  "Which of the following statements about the dipolarity of the water molecule are true?I.\\hspace{1em}Oxygen attracts the shared electrons stronger than hydrogen.II.\\hspace{.7em}Hydrogen atoms are partially negative.III.\\hspace{.4em}The shared electrons spend more time closer to oxygen.A.\\hspace{1em}I and IIB.\\hspace{1em}II and IIIC.\\hspace{1em}I and IIID.\\hspace{1em}I, II, and III",
  "Which of the following isnota reason that scientists look for the presence of water on planets as a sign of extraterrestrial life?A.\\hspace{1em}Water is a necessary resource for most living organismsB.\\hspace{1em}Most enzymes catalyse reactions in solutions containing waterC.\\hspace{1em}Water molecules can stick to each otherD.\\hspace{1em}Water is a universal solvent",
  "The table provides information on planets within a distant galaxy that are a similar size to Earth. Which planet is most likely to be able to support life as we know it on Earth?Gases in the atmosphereSurface temperature /°\\degree°CIs there evidence of water being present?A.\\hspace{1em}Oxygen and carbon dioxide- 45YesB.\\hspace{1em}Nitrogen and sulfur dioxide15YesC.\\hspace{1em}Oxygen and hydrogen100YesD.\\hspace{1em}Helium and hydrogen450No",
  "The cohesive and adhesive properties of water allow xylem vessels to transport water inside plants.Which of the following are correct descriptions of how these properties are related to water transport in plants?CohesiveAdhesive\\hspace{1em}A.\\hspace{1em}Polar water molecules are attracted to one another and form hydrogen bonds.Polar water molecules are attracted to the hydrophilic cell walls in xylem.\\hspace{1em}B.\\hspace{1em}Water molecules are polar, so are able to dissolve ionsPolar water molecules are attracted to one another and form hydrogen bonds.\\hspace{1em}C.\\hspace{1em}Polar water molecules are attracted to one another and form oxygen bonds.Water molecules are polar, so are able to dissolve ions\\hspace{1em}D.\\hspace{1em}Polar water molecules are attracted to the hydrophilic cell walls in xylem.Polar water molecules are attracted to one another and form hydrogen bonds.",
  "The image shows a water strider (G. lacustris) on the surface of a pond. What property of water is not depicted in the image?\n\n![SkillUpp Image](https://assets.revisionvillage.com/public/question/5f81029b-de8d-4958-a391-8fbc42cbbe3a/images/59e027ec-d597-4a15-a9f6-8f2f194143b9/BI1013.png)\n\n[Source adapted from: Zinogre. (2021, July 11).File: Aquarius paludum 142592609.jpg. Wikimedia Commons. Retrieved July, 04 2023, from https://commons.wikimedia.org/wiki/File: Aquarius_paludum_142592609.jpg. Copyright free]A.\\hspace{1em}AdhesionB.\\hspace{1em}Exertion of buoyant forcesC.\\hspace{1em}CohesionD.\\hspace{1em}Thermal conductivity",
  "Which term to describe a property of water is matched to its correct definition?TermDefinitionA.\\hspace{1em}Exerts buoyant forcesMuch energy is required to turn water into a vapourB.\\hspace{1em}High specific heat capacityMuch energy is required to raise the temperature of 1kg water by 1 °CC.\\hspace{1em}High boiling pointTurns from ice into steam at 100 °CD.\\hspace{1em}Low viscosityEasily allows objects to float on the surface",
  "The photograph below is of the sea oat (Unola paniculata). This plant is found on sand dunes.\n\n![SkillUpp Image](https://assets.revisionvillage.com/public/question/1af502cc-5332-4529-ac1e-57e68511c43f/images/54f3a7af-d48b-4bb1-9278-4e35299e8584/BI1424.png)\n\n[Source: Adapted from Daniel Di Palma (2 Feb 2017)Miami Beach - Sand Dune Flora - Sea Oats in South Beach. Retrieved 31 Jan 2024 from https://commons.wikimedia.org/w/index.php?curid=59792482. Copyright CC BY-SA 4.0]Explain how the sea oat (Unola paniculata) is adapted to survive in its environment.[3]Describe the importance of the solvent properties of water for transport in plants and humans.[3]",
  "The image shows a ringed seal (Pusa hispida) that lives in the Arctic Sea.\n\n![SkillUpp Image](https://assets.revisionvillage.com/public/question/4b6b08e8-875d-4ac4-abba-a9c4c27a129b/images/d4b9a85b-c422-4e0a-b290-37d692fd87be/BI0835.png)\n\n[Source: Adapted from: Kingfisher. (2021, May 29). Pusa hispida. Wikimedia Commons. Retrieved from July 07, 2023, from https://commons.wikimedia.org/wiki/Pusa_hispida. Copyright free]Distinguish between the physical properties of air and water that allow the seal to mostly live in the sea.[2]Ringed seals glide into the water head first from ice shelves, rather like humans diving into a pool head first. Explain the advantage of entering the water in this way rather than ‘belly-flopping’ into the water.[2]",
  "Which of the following thermal properties of water isincorrectlymatched?PropertyWaterA.\\hspace{1em}Melting Point0°\\degree°CB.\\hspace{1em}Specific Heat Capacity2.2 Jg−1\\text{g}^{-1}g−1°C−1\\degree \\text{C}^{-1}°C−1C.\\hspace{1em}Latent Heat of Vaporisation760 Jg−1\\text{g}^{-1}g−1D.\\hspace{1em}Boiling Point100°\\degree°C",
  "Below is a picture of a water strider (Gerrissp.\\textit{Gerris sp.}Gerris sp.).\n\n![SkillUpp Image](https://assets.revisionvillage.com/public/question/acd82ba4-e9b6-4ad4-9ae7-0cba2f0322ee/images/98250f20-3d55-4380-b054-95cf70aeb72c/BI0187i_2.2.png)\n\n[Source: Schnobby. (2010).Water Strider. Wikimedia Commons. Retrieved April 27, 2022, from https://commons.wikimedia.org/wiki/File: Water_strider_in_a_pond.jpg. Copyright by CC BY-SA 3.0]Explain why the water strider (Gerrissp.\\textit{Gerris sp.}Gerris sp.) does not sink.[2]Describe, using an example, the importance of water as a solvent in living organisms.[3]",
  "The diagram below shows a water column inside a xylem vessel:\n\n![SkillUpp Image](https://assets.revisionvillage.com/public/question/3f1b2aab-acf0-4771-9f33-131080adcc07/images/50f324b6-f19a-4ec4-ad52-e24066bb9bc2/BI2865%20A1.1%20core%20MCQ.jpeg.JPEG)\n\n[Sources: Adapted from Chan, T (26 May 2025),File: Capillary Action in Plants [image]. Retrieved 5 June 2025 from https://upload.wikimedia.org/wikipedia/commons/9/9c/Capillary_Action_in_Plants.jpg. CC BY-SA 4.0]Which of the following best explains how the property illustrated contributes to plant survival?I.Cohesion between molecules allows tension to be transmitted up the xylem.II.Cohesion enables    water to evaporate more easily.III.Adhesion prevents the water column from breaking.A.\\hspace{1em}I onlyB.\\hspace{1em}II and III onlyC.\\hspace{1em}I and III onlyD.\\hspace{1em}I, II, and III",
  "Which statement supports the theory that meteorites are a source of water on Earth?A.\\hspace{1em}Meteorites contain ice with the same water isotopes as those found in Earth’s oceans.B.\\hspace{1em}Meteorites contain ice and simple polypeptides that promote cohesion between water molecules.C.\\hspace{1em}Meteorites contain liquid water that has a similar salinity to Earth’s oceans.D.\\hspace{1em}Meteorites contain ice and compounds that can be dehydrated to release water.",
  "Which of the following isnota real-life example of adhesion?A.\\hspace{1em}Surface tension on the surface of a lakeB.\\hspace{1em}Dew drops hanging off the tip of a blade of grassC.\\hspace{1em}Water coating the surface of the alveoliD.\\hspace{1em}Water sticking to cellulose in cell walls",
  'Why is water considered a "universal solvent," and why is this important for the origin of life?I.\\hspace{1em}It dissolves a wider variety of substances than any other liquid.II.\\hspace{1em}It can dissolve both polar and non-polar molecules.III.\\hspace{1em}It enables complex biochemical reactions by facilitating the interaction of reactants.A.\\hspace{1em}I and II onlyB.\\hspace{1em}II and III onlyC.\\hspace{1em}I and III onlyD.\\hspace{1em}I, II and III',
  "An investigation was carried out into the effects of household detergents on aquatic habitats. Scientists tested the effect of different household detergents on the surface tension of water in order to better understand the impact they may have on organisms living on the surface.A paper clip was folded slightly on one side and rested on the surface of the water, maintained at a constant temperature and contained within a water tank. Drops of detergent solution were slowly added to the water tank until the paperclip sank to the bottom. The volume of detergent solution taken to sink the paperclip was recorded.Detergent solutions were made by adding 5 ml of detergent to 15 ml of water.\n\n![SkillUpp Image](https://assets.revisionvillage.com/public/question/84d7bb7a-360e-4fcc-8359-01fe66042fd4/images/9e71bc21-aad0-4144-8d02-95f90edc6509/BI0769A.png)\n\n[© Revision Village 2022. Created with Chemix (https://chemix.org)]The results are shown in the table.\n\n![SkillUpp Image](https://assets.revisionvillage.com/public/question/84d7bb7a-360e-4fcc-8359-01fe66042fd4/images/f4fd6e73-53ac-412a-9235-7fae1711865e/BI0769B.png)\n\nState the relationship between the volume of detergent solution added and the surface tension of water.[1]For theEasy Cleandetergent, calculate the mean volume of detergent needed to sink the paper clip.[1]Estimate the volume ofEasy Cleandetergent solution it would take to sink 5 paper clips.[1]Stateonevariable, other than those given, which would need to be controlled in this experiment in order to achieve a valid result.[1]Suggestonemethod that could be used to keep the water at a constant temperature.[1]Explain the importance of maintaining water at a constant temperature.[2]Identifyonepotential source of error in the methodology.[1]Suggest why different numbers of drops of detergent solution were needed to sink the paperclip between each type of detergent.[2]",
  "Outline how water is formed at the end of aerobic respiration.[3]Explain how the properties of water allow it to be transported around a plant.[5]Describe how plants transport carbohydrates from source to sink.[7]",
  "The image shows a cross-section of the vascular tissue of a woody dicot stem, showing the annual rings of phloem and xylem.\n\n![SkillUpp Image](https://assets.revisionvillage.com/public/question/a0648fba-391a-4ca2-952b-fa672ea03b0c/images/8191483b-15e2-4be1-b746-75ba3038686a/BI0834.jpg)\n\n[Source: Adapted from: Berkshire Community College Bioscience Image Library. (2014, February 10). FileDicot stem primary xylem in late one year  - wikimedia. Wikimedia commons. Retrieved July 07, 2023, from https://commons.wikimedia.org/wiki/File:Woody_Dicot_Stem_Ray_System_in_Two_Year_Tilia_%2834997659262%29.jpg. Copyright free]Explain how the properties of water allow it to be transported in the xylem.[3]Describe a physical property of water, other than those that are important for the movement of water through the plant, that makes water essential for the survival of plants.[1]Outline why plants cannot use water to transport lipids.[1]If the temperature drops to -1oC for a few hours suggest a reason why the water in xylem may not freeze.[1]",
  "Which factor determined primarily whether water from asteroids remained on Earth rather than escaping into space?A.\\hspace{1em}The presence of greenhouse gases which insulates Earth and prevents the loss of water vapour to space.B.\\hspace{1em}The presence of autotrophic prokaryotes which photolysed water from the atmosphere in photosynthesis.C.\\hspace{1em}The strength of Earth’s gravitational field which prevents water from diffusing into space.D.\\hspace{1em}The favourable range of temperatures on Earth allowing water to exist in solid, liquid and gaseous states.",
  "Outline how the properties of water contributed to the origin of life on Earth.[4]Drawtwowater molecules, labelling the partial charges and the bond between them.[3]Explain how the solubility of different types of substances in water affects their transport in the blood, giving named examples.[8]",
  "Explain four properties of water that make it important in supporting life on Earth.[4]Describe the recent methods used to reclassify plant groups, such as the figwort family (Scrophulariaceae), based on cladistic evidence.[4]Explain how the structure of synovial joints is adapted for movement and why this influences the range of motion.[7]",
  "The pie chart shows the chemical composition of the Murchison meteorite, which fell in Australia in 1969. It belongs to a class of meteorites called carbonaceous chondrites, some of the solar system's oldest meteorites.\n\n![SkillUpp Image](https://assets.revisionvillage.com/public/question/210d3150-cd6a-4174-8d1f-cc22525eefb0/images/40e6296f-45e6-47b9-971c-c0b71b2d93a3/BI2783.png)\n\n[Source: Adapted from Braukmuller, N., Wombacher, F., Hezel, D. C., Escoube, R., & Munker, C. (2018, July 24). The chemical composition of carbonaceous chondrites: Implications for volatile element depletion, complementarity and alteration. ScienceDirect. Retrieved March 24, 2025 from https://www.sciencedirect.com/science/article/pii/S0016703718304095. Copyright under CC BY 4.0]Explain why analysis of carbonaceous chondrites has led to the hypothesis that meteorites are most likely to be the source of water on Earth.[2]Explaintwoproperties of water that make it an essential molecule for life.[2]Other than water, deduce with a reasonone other substancefound on the Murchison meteorite that is essential for life.[1]The ‘Goldilocks’ zone is the area around a star, where the conditions are optimal for the presence of liquid water.Other than liquid water, statetwoproperties that a planet in the Goldilocks zone may need for life to evolve.[2]Carbonaceous chondrites have also collided with planets in the solar system that are outside the ‘Goldilocks zone’. Suggest why life may not have appeared on those planets.[2]If a planet within the ‘Goldilocks zone’does nothave an atmosphere, suggest how this would affect the retention of liquid water.[1]",
  "The black-throated loon (Gavia arctica) is a bird that lives near large bodies of water in cold climates.  Which of the following is a correct description of how the properties of water may make winter temperatures more moderate for the black-throated loon?A.\\hspace{1em}Water has a relatively high specific heat capacity which buffers the environmental temperature.B.\\hspace{1em}Ice floats on water so insulates the liquid water beneath the ice.C.\\hspace{1em}Water has a low specific heat capacity which warms the surrounding air.D.\\hspace{1em}Water is dense which enables the black-throated loon to float.",
  "Which property describes water’s ability to associate with a wide range of other compounds, and how did this property help retain water on early Earth before the emergence of life?Property of waterHow did this property help retain water on Earth?A.\\hspace{1em}High heat capacityMinimised temperature fluctuations that would evaporate waterB.\\hspace{1em}Universal solventAllowed a wide range of condensation reactions to occur, so water is trapped in biological polymersC.\\hspace{1em}PolarityAllowed water to interact with minerals so that it is stored in hydrated rocksD.\\hspace{1em}Low densityPrevented water from sinking through the surface of the Earth into the mantle",
  "The diagram shows a solar system very similar to ours, where five planets orbit a central star.\n\n![SkillUpp Image](https://assets.revisionvillage.com/public/question/d1815dc7-50c2-4579-afea-9498544e0f6d/images/b5e55501-0c1e-425e-8da0-e61f7243b9e5/BI1018.png)\n\n[© Revision Village 2023]Define the term “Goldilocks zone”.[1]Label with the letter R the planet that is least likely to have extraterrestrial life present.[1]Explain reasons for your answer to part (i).[3]Some of the planets in this solar system have water present on them. Suggest where this water might have come from.[1]Explain why the planets referred to in part (i) have retained water, whereas others in this solar system have not.[2]Suggest one other biological molecule, other than water, that may be a sign of life on a planet.[1]",
  "Which of the following statements explains how water has facilitated the evolution of life on Earth?A.\\hspace{1em}Water acts as a catalyst for chemical reactionsB.\\hspace{1em}Water acts as a solvent allowing chemical reactions to occur faster within itC.\\hspace{1em}Water acts in hydrolysis reactions allowing for the synthesis of large biological moleculesD.\\hspace{1em}Water has a high latent heat of vaporisation so is able to convert between states easily",
  "Which of the following statement(s) about the role of water as a solvent is correct?I.Salt can dissolve in water because it is hydrophilicII.Lipids cannot dissolve in water because they are non-polarIII.Cellulose can dissolve in water, as it is able to form hydrogen bondsA.\\hspace{1em}I onlyB.\\hspace{1em}I and III onlyC.\\hspace{1em}I and II onlyD.\\hspace{1em}I, II and III",
  "Which of the following are a reason why water's properties would have influenced early cellular evolution in aquatic environments?I.High surface tension allowing formation of proto-cell membranes.II.Polar solvent properties enabling interaction of biomolecules.III.High density causing rapid sedimentation of organic material.A.\\hspace{1em}I onlyB.\\hspace{1em}II onlyC.\\hspace{1em}II and III onlyD.\\hspace{1em}I and III only",
]; // 从页面获取

// 1. 读取文件内容
const data = JSON.parse(fs.readFileSync(filePath, "utf8"));

// 2. 修改字段

const group = [];
data.list.forEach((item) => {
  if (questionArr.includes(item.content)) {
    group.push(item);
  }
});

// 3. 写回文件（格式化缩进 2 个空格）
fs.writeFileSync(newPath, JSON.stringify({ list: group }, null, 2), "utf8");

console.log("✅ JSON 文件已更新！");
